trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install dependencies'

- script: npm run build-prod
  displayName: 'Build Angular app'

# Archive les fichiers de build Angular
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/pfe-frontend/browser'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive Angular build output'

# Déploiement vers Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-connection-pfe'
    appName: 'pfe-frontend-app'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy Angular app to Azure Web App'
