trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.13.1'

- script: |
    npm ci
    npm run build --prod
  displayName: 'Install & Build Angular App'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-connection-pfe'
    appName: 'pfe-frontend-app'
    package: '$(System.DefaultWorkingDirectory)/dist/pfe-frontend'
